### ISSUE TITLE
No Store class or Products, Orders, etc

### ISSUE THREAD

**Issue by emerika** [Weebly/cloud-client-php#4]
Has anyone or is anyone working on adding these? 

Just checking before I start adding them myself.

**Comment by szainmehdi** [comment]
We don't have immediate plans to add classes for these resources just yet. Feel free to add the classes and create a PR!

In the meantime, you could always make raw API calls using the client directly:

```php
use WeeblyCloud\Utils\CloudClient;

CloudClient::setKeys(YOUR_API_KEY, YOUR_API_SECRET);

$client = CloudClient::getClient();
$response = $client->get('user/35000103/site/537865958129511201/store');

$data = json_decode($response->body);
```
