### ISSUE TITLE
Non-static method should not be called statically

### ISSUE THREAD

**Issue by Tpojka** [Weebly/cloud-client-php#5]
That is an error I have got when I was trying to instantiate object. I was able to resolve that issue by adding keyword static to the method. 

vendor/weebly/cloud-client/src/Utils/CloudClient.php:62

    /**
       * Sets the instance of CloudClient using the API keys. Must
       * be called before making a request.
       *
       * @param string $api_key
       * @param string $api_secret
       */
      public static function setKeys($api_key, $api_secret) {
          static::$instance = new static($api_key, $api_secret);
      }

**Comment by Tpojka** [comment]
Ok, issue was that documentation should point `composer require weebly/cloud-client:dev-master`. It is solved in such a way, but still some issues that are pointed in [here](https://github.com/Weebly/cloud-client-php/pull/3/commits/b15a40a9e972eaf656eed033a28e3359f3243a6c).

**Comment by szainmehdi** [comment]
As you've pointed out, this issue has been addressed already. Closing this issue.
